version: "3.7"
services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lottery
      - MYSQL_USER=lottery

  php:
    image: antonds/lottery-php:7.4-fpm
    container_name: php
    volumes:
      - ./core:/home/www/core
    links:
      - mysql:mysql

  web:
    image: antonds/lottery-web:latest
    container_name: web
    ports:
      - "8181:80"
    volumes:
      - ./core:/home/www/core
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
